language: ruby
rvm:
  - "2.1.2"
services:
  - neo4j
env:
  - NEO_VERSION="2.1.4"

before_install:
  - wget dist.neo4j.org/neo4j-community-$NEO_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO_VERSION-unix.tar.gz
  - neo4j-community-$NEO_VERSION/bin/neo4j start